#!/bin/bash

#git remote add upstream https://github.com/terraform-linters/tflint.git
#git fetch upstream
#git checkout master
#git pull
#git merge <tag> -m "Merging upstream tag <tag>"
#git tag -d <tag>
#git tag -a <tag>
#git push origin <tag>

